### ISSUE TITLE
请求http://localhost:3000/client.action为404

### ISSUE THREAD

**Issue by RoneLeo** [DiscoverForever/flutter_mock_server#1]
我下载后，npm i 后 npm start 启动之后，/client.action为404，但 / 和 /users 是正常的。

**Comment by DiscoverForever** [comment]
仅支持/client.action?functionId=xxxx的POST请求，会根据functionId取对应的JSON文件作为mock数据返回。 直接请求/client.action是会返回404的不影响flutter项目运行。
