### ISSUE TITLE
接口返回 404，没有npm 经验

### ISSUE THREAD

**Issue by Seachal** [DiscoverForever/flutter_mock_server#2]
## http://localhost:3000/ 访问正常
![image](https://user-images.githubusercontent.com/14776606/103078217-5d12d800-460c-11eb-861f-640954b1494b.png)

## http://localhost:3000/client.action?functionId=personinfoBusiness
![image](https://user-images.githubusercontent.com/14776606/103078155-3ce31900-460c-11eb-81bd-c9de4649a778.png)

**Comment by DiscoverForever** [comment]
Mock服务提供的接口 请求类型是POST，直接使用浏览器访问默认发送的是GET请求，所以访问不到。
localhost:3000可以访问 证明服务已经启动成功，APP端已经可以正常访问。 
如需查看请求返回值，可以使用Postman调试工具 发送POST请求查看。
